apiVersion: v1
kind: Service
metadata:
  name: service-for-user-{pod_name}
spec:
  type: ClusterIP
  selector:
    user-id: {pod_name} # PodのセレクターにユーザーIDを使用
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
